name: Feature request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: checkboxes
    attributes:
      label: Basics
      options:
        - label: I have done a basic search through the issue tracker to find similar or related issues.
        - label: I have made myself familiar with the available features of spotify_web_api for the particular area this enhancement request touches.

  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of what new feature or behavior you would like to see. If applicable, please describe the current behavior as well.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Example
      description: Provide an example of how the user experience would change or how the new feature would be used.
    validations:
      required: false
